name: ai_datasets_trainer
description: A trainer for AI datasets
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hexcolor: ^3.0.1
  http: ^0.13.5
  path_provider: ^2.0.14
  textfield_tags: ^2.0.2
  universal_io:  ^2.2.0
  ftpconnect: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true